services:
  api:
    build:
      context: ../backend          # CORREGIDO: Sube un nivel para encontrar 'backend'
      dockerfile: dockerfile       # CORREGIDO: Usa 'dockerfile' en minúsculas
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app            # CORREGIDO: Sube un nivel
      - ../docs:/app/docs          # CORREGIDO: Sube un nivel
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - rag-network

  ui:
    build:
      context: ../ui               # CORREGIDO: Sube un nivel para encontrar 'ui'
      dockerfile: dockerfile       # CORREGIDO: Usa 'dockerfile' en minúsculas
    ports:
      - "7860:7860"
    volumes:
      - ../ui:/app                 # CORREGIDO: Sube un nivel
    working_dir: /app
    command: streamlit run app.py --server.port=7860 --server.address=0.0.0.0
    networks:
      - rag-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_storage:
  ollama:
