version: '3.9'

services:
  api:
    build:
      context: . 
      dockerfile: backend/Dockerfile # CORREGIDO: 'Dockerfile' con mayúscula
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    working_dir: /app
    # CORREGIDO: Se añade la ruta 'backend.' al módulo de Python
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    networks: 
      - rag-network

  ui:
    build:
      context: . 
      dockerfile: ui/Dockerfile # CORREGIDO: 'Dockerfile' con mayúscula
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    working_dir: /app
    # CORREGIDO: Se añade la ruta completa al script de Streamlit
    command: streamlit run ui/app.py --server.port=7860 --server.address=0.0.0.0
    networks: 
      - rag-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks: 
      - rag-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks: 
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_storage:
  ollama:
