# ui/Dockerfile

# Paso 1: Usar la misma imagen base de Python para mantener la consistencia.
FROM python:3.9-slim

# Paso 2: Establecer el directorio de trabajo.
WORKDIR /app

# Paso 3 y 4: Instalar dependencias directamente desde el Dockerfile
# Misma técnica 'heredoc' para el frontend.
RUN <<EOF
pip install --no-cache-dir \
    streamlit \
    requests
EOF

# Paso 5: Copiar el resto del código de la interfaz de usuario.
COPY . .

# Paso 6: El comando para ejecutar la aplicación Streamlit.
# De nuevo, es buena práctica tenerlo aquí aunque docker-compose.yml lo anule.
CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.address=0.0.0.0"]
